CREATE TABLE IF NOT EXISTS "entry" (
    "EntryId" INTEGER NOT NULL CONSTRAINT "PK_entry" PRIMARY KEY AUTOINCREMENT,
    "Change" TINYINT NOT NULL,
    "ContainerId" INTEGER NULL,
    "IsContained" TINYINT NOT NULL,
    "IsCurrent" TINYINT NOT NULL,
    "LastUpdated" DATETIME NOT NULL,
    "Reference" TEXT COLLATE NOCASE NULL,
    "ResourceId" TEXT COLLATE BINARY NULL,
    "ResourceJson" TEXT COLLATE BINARY NULL,
    "Type" TEXT COLLATE NOCASE NULL,
    "Version" TEXT COLLATE BINARY NULL,
    CONSTRAINT "FK_entry_entry_ContainerId" FOREIGN KEY ("ContainerId") REFERENCES "entry" ("EntryId") ON DELETE RESTRICT
);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "dt" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_dt" PRIMARY KEY AUTOINCREMENT,
    "End" DATETIME NULL,
    "EntryId" INTEGER NOT NULL,
    "Name" TEXT COLLATE BINARY NULL,
    "Start" DATETIME NULL,
    CONSTRAINT "FK_dt_entry_EntryId" FOREIGN KEY ("EntryId") REFERENCES "entry" ("EntryId") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "num" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_num" PRIMARY KEY AUTOINCREMENT,
    "EntryId" INTEGER NOT NULL,
    "Name" TEXT COLLATE BINARY NULL,
    "Value" DECIMAL(38,10) NOT NULL,
    CONSTRAINT "FK_num_entry_EntryId" FOREIGN KEY ("EntryId") REFERENCES "entry" ("EntryId") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "qty" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_qty" PRIMARY KEY AUTOINCREMENT,
    "Amount" DECIMAL(38,10) NOT NULL,
    "CAmount" TEXT COLLATE NOCASE NULL,
    "CCode" TEXT COLLATE NOCASE NULL,
    "Code" TEXT COLLATE NOCASE NULL,
    "EntryId" INTEGER NOT NULL,
    "Name" TEXT COLLATE BINARY NULL,
    "System" TEXT COLLATE NOCASE NULL,
    "Unit" TEXT COLLATE NOCASE NULL,
    CONSTRAINT "FK_qty_entry_EntryId" FOREIGN KEY ("EntryId") REFERENCES "entry" ("EntryId") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "ref" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_ref" PRIMARY KEY AUTOINCREMENT,
    "EntryId" INTEGER NOT NULL,
    "Name" TEXT COLLATE BINARY NULL,
    "RelativeReference" TEXT COLLATE NOCASE NULL,
    "Url" TEXT COLLATE BINARY NULL,
    "UrlHash" TEXT COLLATE BINARY NULL,
    CONSTRAINT "FK_ref_entry_EntryId" FOREIGN KEY ("EntryId") REFERENCES "entry" ("EntryId") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "str" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_str" PRIMARY KEY AUTOINCREMENT,
    "EntryId" INTEGER NOT NULL,
    "Hash" TEXT COLLATE BINARY NULL,
    "LongString" TEXT COLLATE NOCASE NULL,
    "Name" TEXT COLLATE BINARY NULL,
    "ShortString" TEXT COLLATE NOCASE NULL,
    CONSTRAINT "FK_str_entry_EntryId" FOREIGN KEY ("EntryId") REFERENCES "entry" ("EntryId") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "tkn" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_tkn" PRIMARY KEY AUTOINCREMENT,
    "Code" TEXT COLLATE NOCASE NULL,
    "EntryId" INTEGER NOT NULL,
    "Name" TEXT COLLATE BINARY NULL,
    "SystemValue" TEXT COLLATE BINARY NULL,
    "SystemHash" TEXT COLLATE BINARY NULL,
    "Text" TEXT COLLATE NOCASE NULL,
    CONSTRAINT "FK_tkn_entry_EntryId" FOREIGN KEY ("EntryId") REFERENCES "entry" ("EntryId") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "uri" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_uri" PRIMARY KEY AUTOINCREMENT,
    "EntryId" INTEGER NOT NULL,
    "Name" TEXT COLLATE BINARY NULL,
    "UriValue" TEXT COLLATE BINARY NULL,
    "UriHash" TEXT COLLATE BINARY NULL,
    CONSTRAINT "FK_uri_entry_EntryId" FOREIGN KEY ("EntryId") REFERENCES "entry" ("EntryId") ON DELETE CASCADE
